### ISSUE TITLE
[marketplace-integrated-saas]:

### ISSUE THREAD

**Issue by andy-rose-pantheon** [googlecodelabs/gcp-marketplace-integrated-saas#15]
On step 4, the create_subscription.py script doesn't seem to work. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andyrose/.pyenv/versions/3.7.5/lib/python3.7/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
TypeError: create_subscription() takes from 1 to 2 positional arguments but 3 were given
```

Looking through it, I'm not sure that we would have access to the project 'cloudcommerceproc-prod', but that doesn't seem to be why it failed. When trying to create the subscription in the UI, I am not able to find 'cloudcommerceproc-prod'.

**Comment by Moonwalker7** [comment]
This worked for me

`subscription = subscriber.create_subscription(
            request={"name": subscription_path, "topic": topic_path}
        )`
